version: "3"

volumes:
  postgresdata:
  mongodata:
  clickhousedata:
  redisdata:
  rabbitmqdata:
  tarantooldata:

services:
  mongo-db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartdom
      MONGO_INITDB_ROOT_PASSWORD: smartdom
  postgres-db:
    image: postgres:14.6-alpine
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: smartdom
      POSTGRES_USER: smartdom
      POSTGRES_DB: smartdom
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    tty: true
    command:
      - start-dev
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  redis-db:
#    image: redis:6.2-alpine
    image: redis/redis-stack
#    hostname: redis
#    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redisdata:/data
#  clickhouse-zookeeper:
#    image: zookeeper
#    ports:
#      - "2181:2181"
#      - "2182:2182"
#    container_name: clickhouse-zookeeper
#    hostname: clickhouse-zookeeper
  clickhouse-db:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
       - clickhousedata:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: smartdom
      CLICKHOUSE_USER: smartdom
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: smartdom
#    depends_on:
#      - clickhouse-zookeeper
  tarantool-db:
    image: tarantool/tarantool
    volumes:
      - tarantooldata:/opt/tarantool
    environment:
      TARANTOOL_USER_NAME: "smartdom"
      TARANTOOL_USER_PASSWORD: "smartdom"
    ports:
      - "3301:3301"